# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwBk-2YFI83-q0lIWbWtUOUivCq2a1Ny
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as npy
import pandas as pds
import matplotlib.pyplot as plt
# %matplotlib inline

bt_dataset=pds.read_csv("healthcare-dataset-stroke-data.csv")

bt_dataset.head()

bt_dataset.shape

bt_dataset.info()

bt_dataset.describe()

bt_dataset.isna().sum()

bt_dataset.columns

from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
bt_dataset['bmi'] = imputer.fit_transform(bt_dataset[['bmi']])

bt_dataset.isna().sum()

bt_dataset['smoking_status'].value_counts()

bt_dataset.smoking_status.unique()

bt_dataset.info()

bt_dataset.gender.value_counts()

gender = pds.get_dummies(bt_dataset[['gender']],drop_first=True)
gender.head()

married=pds.get_dummies(bt_dataset[['ever_married']],drop_first=True)
married.head()

work = pds.get_dummies(bt_dataset[['work_type']],drop_first=True)
work.head()

residence=pds.get_dummies(bt_dataset[['Residence_type']],drop_first=True)
residence.head()

smoking = pds.get_dummies(bt_dataset[['smoking_status']],drop_first=True)
smoking.head()

data=pds.concat([bt_dataset,gender,married,work,residence,smoking],axis=1)
data.head()

data.head()

numerical_feature=['age',]

z=data.drop("stroke",axis=1)
z.head()

x=data.drop("gender",axis=1)
x.head()

y=data[['stroke']]
y.head()

